### ISSUE TITLE
DB Event inbound not supporting CLOB columns 

### ISSUE THREAD

**Issue by VirajHasitha** [wso2-extensions/esb-inbound-dbevent#16]
**Description:**
Cannot retrieve the CLOB column data in Oracle DB using the DB Event inbound.

**Affected Product Version:**
Enterprise Integrator

**OS, DB, other environment details and versions:**    
Oracle DB

**Steps to reproduce:**
Use DB Event inbound to retrieve the data from a table where it contains a column with a CLOB data type gives the following error.

`ERROR - DBEventPollingConsumer Unsupported column type 2005`

**Comment by anupama-pathirage** [comment]
Moved to https://github.com/wso2/micro-integrator/issues/3524
