### ISSUE TITLE
Error occured when we use this with H2 databse

### ISSUE THREAD

**Issue by Biruntha** [wso2-extensions/esb-inbound-dbevent#8]
**Description:**
org.h2.jdbc.JdbcSQLException: This method is not allowed for a prepared statement; use a regular statement instead. [90130-175]

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by abeykoon** [comment]
This issue is fixed with PR above.
